apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bitcoin-bastion-single-node

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patch-env.yaml
  - path: patch-resources.yaml
  - path: patch-single-node-replicas.yaml
  - path: patch-disable-heavy-jobs.yaml
  - path: patch-disable-hpa.yaml
