apiVersion: v1
kind: Namespace
metadata:
  name: bitcoin-bastion-single-node
  labels:
    app.kubernetes.io/name: bitcoin-bastion
    app.kubernetes.io/environment: single-node
    app.kubernetes.io/runtime-profile: single-node
