apiVersion: v1
kind: ConfigMap
metadata:
  name: bitcoin-bastion-config
  namespace: bitcoin-bastion
data:
  ENVIRONMENT: "staging"
  UVICORN_HOST: "0.0.0.0"
  UVICORN_PORT: "8000"
  LOG_LEVEL: "info"
