apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bitcoin-bastion-api
  namespace: bitcoin-bastion
spec:
  selector:
    matchLabels:
      app: bitcoin-bastion-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
