"""Reason codes for Bastion Access Policy Engine decisions."""

ACCESS_ALLOWED = "access_allowed"
MISSING_ACCESS_CONTEXT = "missing_access_context"
CERTIFICATE_EXPIRED = "certificate_expired"
CERTIFICATE_REVOKED = "certificate_revoked"
ENTITLEMENT_EXPIRED = "entitlement_expired"
ENTITLEMENT_INACTIVE = "entitlement_inactive"
SESSION_EXPIRED = "session_expired"
SESSION_REVOKED = "session_revoked"
DEVICE_REVOKED = "device_revoked"
DEVICE_RISK_TOO_HIGH = "device_risk_too_high"
SCOPE_NOT_ALLOWED = "scope_not_allowed"
METRIC_NOT_ALLOWED = "metric_not_allowed"
METRIC_REQUIRES_HIGHER_PLAN = "metric_requires_higher_plan"
QUOTA_EXCEEDED = "quota_exceeded"
OBJECT_ACCESS_DENIED = "object_access_denied"
BUSINESS_ROLE_DENIED = "business_role_denied"
CRITICAL_ACTION_REQUIRES_STEP_UP = "critical_action_requires_step_up"
CRITICAL_ACTION_REQUIRES_HUMAN_INTENT = "critical_action_requires_human_intent"
OFFLINE_ACCESS_NOT_ALLOWED = "offline_access_not_allowed"
ONLINE_CHECK_REQUIRED = "online_check_required"
RECOVERY_REQUIRED = "recovery_required"
LOCKDOWN_REQUIRED = "lockdown_required"
LEGACY_AUTH_NOT_ALLOWED = "legacy_auth_not_allowed"
