"""Pure wallet auth domain primitives."""

from app.domain.wallet_auth.actions import (
    CRITICAL_WALLET_ACTIONS,
    WalletAuthAction,
    is_critical_wallet_action,
)
from app.domain.wallet_auth.constants import (
    DEDICATED_AUTH_ADDRESS_WARNING,
    FORBIDDEN_WALLET_SECRET_TERMS,
    REQUIRED_SIGNATURE_WARNING,
    WALLET_AUTH_INTENT_TYPE,
    WALLET_AUTH_INTENT_VERSION,
)
from app.domain.wallet_auth.devices import (
    NON_ROOT_OF_TRUST_DEVICE_CLASSES,
    WalletDeviceClass,
    WalletDeviceStatus,
    is_root_of_trust_device_class,
)
from app.domain.wallet_auth.errors import (
    UnsupportedWalletNetworkError,
    UnsupportedWalletProofTypeError,
    WalletActionRequiresStepUpError,
    WalletAuthDomainError,
    WalletDeviceRevokedError,
    WalletPrincipalRevokedError,
    WalletPrincipalSuspendedError,
    WalletProofTooWeakError,
    WalletRecoveryNotAllowedError,
    WalletSecretInputForbiddenError,
    WalletSessionInvalidError,
)
from app.domain.wallet_auth.hardware import (
    HardwareWalletAssuranceLevel,
    HardwareWalletBindingType,
    HardwareWalletEvidenceStatus,
    HardwareWalletEvidenceType,
    HardwareWalletIntentDisplayState,
    HardwareWalletInteractionMode,
    hardware_assurance_at_least,
)
from app.domain.wallet_auth.networks import (
    DEFAULT_PRODUCTION_NETWORK,
    WalletNetwork,
    is_production_network,
    is_test_network,
)
from app.domain.wallet_auth.principals import WalletPrincipalActorType, WalletPrincipalStatus
from app.domain.wallet_auth.proofs import (
    COMPATIBILITY_ONLY_PROOF_TYPES,
    WalletProofType,
    WalletScriptType,
    WalletVerificationStrength,
    is_strength_at_least,
    verification_strength_rank,
)
from app.domain.wallet_auth.quorum import (
    QuorumDecision,
    QuorumEvaluation,
    QuorumFailureReason,
    QuorumParticipantSlot,
    QuorumParticipantType,
    QuorumPolicy,
    QuorumProofMethod,
    QuorumStatus,
    QuorumType,
    VerifiedQuorumApproval,
)
from app.domain.wallet_auth.recovery import (
    BUSINESS_RECOVERY_FACTORS,
    ENTERPRISE_RECOVERY_FACTORS,
    LITE_BASIC_RECOVERY_FACTORS,
    PLUS_PRO_RECOVERY_FACTORS,
    SOVEREIGN_RECOVERY_FACTORS,
    RecoveryFactorType,
    WalletRecoveryProfile,
)
from app.domain.wallet_auth.risks import (
    DEFAULT_WALLET_ACTION_RISK,
    WalletRiskLevel,
    default_risk_for_action,
    is_compatibility_strength_allowed_for_action,
    is_strength_allowed_for_action,
)
from app.domain.wallet_auth.sessions import (
    DEFAULT_STEP_UP_TTL_SECONDS,
    DEFAULT_WALLET_CHALLENGE_TTL_SECONDS,
    DEFAULT_WALLET_SESSION_TTL_SECONDS,
    WalletSessionStatus,
)

__all__ = [
    "BUSINESS_RECOVERY_FACTORS",
    "COMPATIBILITY_ONLY_PROOF_TYPES",
    "CRITICAL_WALLET_ACTIONS",
    "DEDICATED_AUTH_ADDRESS_WARNING",
    "DEFAULT_PRODUCTION_NETWORK",
    "DEFAULT_STEP_UP_TTL_SECONDS",
    "DEFAULT_WALLET_ACTION_RISK",
    "DEFAULT_WALLET_CHALLENGE_TTL_SECONDS",
    "DEFAULT_WALLET_SESSION_TTL_SECONDS",
    "ENTERPRISE_RECOVERY_FACTORS",
    "FORBIDDEN_WALLET_SECRET_TERMS",
    "LITE_BASIC_RECOVERY_FACTORS",
    "hardware_assurance_at_least",
    "HardwareWalletInteractionMode",
    "HardwareWalletIntentDisplayState",
    "HardwareWalletEvidenceType",
    "HardwareWalletEvidenceStatus",
    "HardwareWalletBindingType",
    "HardwareWalletAssuranceLevel",
    "NON_ROOT_OF_TRUST_DEVICE_CLASSES",
    "PLUS_PRO_RECOVERY_FACTORS",
    "REQUIRED_SIGNATURE_WARNING",
    "QuorumDecision",
    "QuorumEvaluation",
    "QuorumFailureReason",
    "QuorumParticipantSlot",
    "QuorumParticipantType",
    "QuorumPolicy",
    "QuorumProofMethod",
    "QuorumStatus",
    "QuorumType",
    "RecoveryFactorType",
    "SOVEREIGN_RECOVERY_FACTORS",
    "UnsupportedWalletNetworkError",
    "UnsupportedWalletProofTypeError",
    "WALLET_AUTH_INTENT_TYPE",
    "WALLET_AUTH_INTENT_VERSION",
    "WalletActionRequiresStepUpError",
    "WalletAuthAction",
    "WalletAuthDomainError",
    "WalletDeviceClass",
    "WalletDeviceRevokedError",
    "WalletDeviceStatus",
    "WalletNetwork",
    "WalletPrincipalActorType",
    "WalletPrincipalRevokedError",
    "WalletPrincipalStatus",
    "WalletPrincipalSuspendedError",
    "WalletProofTooWeakError",
    "WalletProofType",
    "WalletRecoveryNotAllowedError",
    "WalletRecoveryProfile",
    "WalletRiskLevel",
    "WalletScriptType",
    "WalletSecretInputForbiddenError",
    "WalletSessionInvalidError",
    "WalletSessionStatus",
    "WalletVerificationStrength",
    "VerifiedQuorumApproval",
    "default_risk_for_action",
    "is_compatibility_strength_allowed_for_action",
    "is_critical_wallet_action",
    "is_production_network",
    "is_root_of_trust_device_class",
    "is_strength_allowed_for_action",
    "is_strength_at_least",
    "is_test_network",
    "verification_strength_rank",
]
