apiVersion: v1
kind: ConfigMap
metadata:
  name: bitcoin-bastion-config
data:
  ENVIRONMENT: "minikube"
  APP_ENV: "minikube"
  DEBUG: "false"
  BBASTION_RUNTIME_PROFILE: "minikube"
  BBASTION_DEPLOYMENT_MODE: "local-kubernetes"
  BBASTION_PROFILE_PRODUCTION_READY: "false"
