"""Public crypto primitives for Bastion Proof-of-Access Auth."""

from app.services.access.crypto.algorithms import (
    CryptoAssuranceLevel,
    CryptoCapabilityStatus,
    EncryptionOrKEMAlgorithm,
    HashAlgorithm,
    SignatureAlgorithm,
)
from app.services.access.crypto.crypto_agility import CryptoCapabilityRegistry
from app.services.access.crypto.issuer_envelope import (
    BastionIssuedObjectType,
    BastionIssuerSignatureEnvelope,
    BastionIssuerSigningService,
    BastionIssuerVerificationService,
    IssuerEnvelopeVerificationResult,
)
from app.services.access.crypto.migration_policy import (
    CryptoEpochPolicy,
    CryptoEpochRegistry,
    SignatureRequirementPolicy,
)

from app.services.access.crypto.signatures import (
    Ed25519SignatureSuite,
    IssuerSignature,
    PQ_KEM_SUITES_KNOWN,
    PQ_SIGNATURE_SUITES_KNOWN,
    SignatureSuiteRegistry,
    SignatureVerificationResult,
    SigningInput,
    build_signing_message,
    sign_access_certificate,
    sign_subscription_entitlement,
    verify_access_certificate_signature,
    verify_device_challenge_signature,
    verify_subscription_entitlement_signature,
)

from app.services.access.crypto.hashing import (
    AUDIT_GENESIS_HASH_INPUT,
    access_pass_commitment,
    access_pass_lookup_hash,
    audit_event_hash,
    body_hash,
    canonical_json,
    certificate_fingerprint,
    constant_time_equal,
    hash_canonical_json,
    hash_canonical_json_prefixed,
    hmac_sha256_hex,
    hmac_sha256_prefixed,
    normalize_bytes,
    reject_forbidden_secret_keys,
    request_digest,
    safe_hash_for_log,
    secure_nonce_hex,
    secure_token_urlsafe,
    sha256_hex,
    sha256_prefixed,
)

__all__ = [
    "BastionIssuedObjectType",
    "BastionIssuerSignatureEnvelope",
    "BastionIssuerSigningService",
    "BastionIssuerVerificationService",
    "CryptoAssuranceLevel",
    "CryptoCapabilityRegistry",
    "CryptoCapabilityStatus",
    "CryptoEpochPolicy",
    "CryptoEpochRegistry",
    "EncryptionOrKEMAlgorithm",
    "HashAlgorithm",
    "IssuerEnvelopeVerificationResult",
    "SignatureAlgorithm",
    "SignatureRequirementPolicy",
    "Ed25519SignatureSuite",
    "IssuerSignature",
    "PQ_KEM_SUITES_KNOWN",
    "PQ_SIGNATURE_SUITES_KNOWN",
    "SignatureSuiteRegistry",
    "SignatureVerificationResult",
    "SigningInput",
    "build_signing_message",
    "sign_access_certificate",
    "sign_subscription_entitlement",
    "verify_access_certificate_signature",
    "verify_device_challenge_signature",
    "verify_subscription_entitlement_signature",
    "AUDIT_GENESIS_HASH_INPUT",
    "access_pass_commitment",
    "access_pass_lookup_hash",
    "audit_event_hash",
    "body_hash",
    "canonical_json",
    "certificate_fingerprint",
    "constant_time_equal",
    "hash_canonical_json",
    "hash_canonical_json_prefixed",
    "hmac_sha256_hex",
    "hmac_sha256_prefixed",
    "normalize_bytes",
    "reject_forbidden_secret_keys",
    "request_digest",
    "safe_hash_for_log",
    "secure_nonce_hex",
    "secure_token_urlsafe",
    "sha256_hex",
    "sha256_prefixed",
]
