apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: {name: bitcoin-bastion-staging, namespace: argocd}
spec:
  project: bitcoin-bastion
  source: {repoURL: https://github.com/Hegehub/bitcoinbastion.git, targetRevision: main, path: deploy/kubernetes/overlays/staging}
  destination: {server: https://kubernetes.default.svc, namespace: bitcoin-bastion-staging}
  syncPolicy: {automated: {prune: true, selfHeal: true}, syncOptions: [CreateNamespace=true]}
