# ruff: noqa: E501
from __future__ import annotations

import reflex as rx

from bastion_ui.components.auth import (
    dedicated_auth_address_notice,
    lightning_address_card,
    lnurl_auth_qr_code,
    lnurl_payment_status,
    subscription_plan_card,
    wallet_auth_method_selector,
    wallet_security_warning,
)
from bastion_ui.components.layout.grid import responsive_grid, three_column_grid
from bastion_ui.components.ui.card import card
from bastion_ui.routes._shared import link_card, public_page

PLAN_CODES = (
    ("Lite", "lite_pass", "Entry access with backend-defined basic capabilities."),
    ("Basic", "basic_pass", "Basic dashboards and backend-enforced read limits."),
    ("Plus", "plus_pass", "Standard market and Trace capabilities when entitled."),
    ("Pro", "pro_pass", "Advanced history, API automation, and stronger recovery policy."),
    (
        "Business",
        "business_pass",
        "Workspace and PayRegister capabilities governed by effective roles.",
    ),
    ("Enterprise", "enterprise_pass", "Deployment-specific limits, quorum, and approval hooks."),
)


def access_page() -> rx.Component:
    return public_page(
        "Bitcoin Bastion Access",
        rx.text(
            "Choose a wallet proof method. Payment, wallet proof, and LNURL-auth are distinct events; protected access requires a Device-bound PoP Session and backend policy approval."
        ),
        rx.text("This is not a password."),
        rx.text("Bastion will never ask for your Bitcoin seed or private key."),
        wallet_auth_method_selector(),
        three_column_grid(
            link_card(
                "Subscription plans",
                "/access/plans",
                "Choose a backend-supported plan and pay externally with LNURL-pay.",
            ),
            link_card(
                "Access Certificate",
                "/access/certificate",
                "Optional high-assurance bridge; never a bearer password.",
            ),
            link_card(
                "Business / Enterprise",
                "/business/access",
                "Deployment capabilities and roles remain backend-defined.",
            ),
        ),
        wallet_security_warning(),
        dedicated_auth_address_notice(),
        subtitle="Wallet-first is not wallet-only. LNURL-native is not LNURL-only.",
    )


def access_plans_page() -> rx.Component:
    return public_page(
        "Subscription plans",
        responsive_grid(*(subscription_plan_card(*plan) for plan in PLAN_CODES)),
        card(
            rx.text(
                "Sovereign Security Mode is a high-assurance policy mode, not a simple subscription tier."
            ),
            title="High assurance",
        ),
        subtitle="The backend entitlement and Policy Engine—not the plan label in this page—determine access.",
    )


def access_checkout_page() -> rx.Component:
    return public_page(
        "LNURL-pay subscription checkout",
        card(
            rx.text(
                "Plan · amount in sats · duration · backend-returned metadata · included capability summary"
            ),
            lnurl_auth_qr_code("LNURL payment request generated by Bastion"),
            title="Pay from an external Lightning wallet",
            subtitle="No wallet action starts automatically. Mobile users can use the encoded Lightning link.",
        ),
        lnurl_payment_status(),
        card(
            rx.text("payerData.auth: allowed/preferred when requested"),
            rx.text("identifier and pubkey: optional only"),
            rx.text("name and email: disabled/optional by default and never auto-filled"),
            rx.text("Payment note: optional, bounded by commentAllowed, and never authorization."),
            title="Privacy-first payer data",
        ),
        subtitle="Creating an invoice is not payment. Settlement is not activation until the backend issues an entitlement.",
    )


def access_payment_page() -> rx.Component:
    return public_page(
        "Payment preparation",
        lightning_address_card(),
        lnurl_payment_status(),
        subtitle="Payment is not authentication.",
    )


def access_payment_pending_page() -> rx.Component:
    return public_page(
        "Payment pending",
        lnurl_payment_status(),
        card(
            rx.text("Re-check settlement through Bastion. Do not rely on wallet UI success alone."),
            title="Backend verification required",
        ),
        subtitle="Status: invoice issued or payment pending—not active.",
    )


def access_success_page() -> rx.Component:
    return public_page(
        "Bastion access activated",
        lnurl_payment_status(),
        card(
            rx.text("A backend-approved successAction message may be displayed safely."),
            rx.text(
                "A successAction URL is shown for deliberate user navigation only after same-origin/allowlist validation. It is never opened automatically."
            ),
            rx.text(
                "URLs must never contain a session token, Access Pass, recovery material, Device private key, or wallet signature."
            ),
            title="Safe success action",
            variant="safety",
        ),
        subtitle="Shown only after backend settlement verification and entitlement activation.",
    )


def access_certificate_page() -> rx.Component:
    return public_page(
        "Access Certificate",
        card(
            rx.text(
                "Create, inspect, import bastion-pass.bbp, revoke, or export only when the deployment exposes the Access Certificate APIs."
            ),
            rx.text(
                "An Access Certificate is an additional Bastion security layer. It does not replace wallet proof, Device Binding, PoP Session, or Policy Engine."
            ),
            title="Optional high-assurance bridge",
        ),
        subtitle="Unavailable actions must remain visibly unavailable rather than producing mock success.",
    )


def access_offline_page() -> rx.Component:
    return public_page(
        "Offline validity",
        card(
            rx.text(
                "Valid until · allowed offline scopes · revocation epoch · Device Binding · issuer status"
            ),
            title="Offline Validity Pack",
            subtitle="Full offline administrator access is not implied.",
        ),
        subtitle="Optional and deployment-controlled.",
    )
