from __future__ import annotations

PUBLIC_ROUTES: tuple[str, ...] = (
    "/",
    "/platform",
    "/access",
    "/access/checkout",
    "/access/plans",
    "/access/payment",
    "/access/payment/pending",
    "/access/payment/success",
    "/access/certificate",
    "/access/offline",
    "/wallet-auth",
    "/wallet-auth/register",
    "/wallet-auth/login",
    "/wallet-auth/lnurl",
    "/wallet-auth/bitcoin",
    "/wallet-auth/session",
    "/wallet-auth/devices",
    "/wallet-auth/entitlements",
    "/wallet-auth/subscription",
    "/wallet-auth/step-up",
    "/wallet-auth/recovery",
    "/wallet-auth/lockdown",
    "/wallet-auth/lightning",
    "/wallet-auth/lightning/pay",
    "/wallet-auth/lightning/withdraw",
    "/wallet-auth/lightning/addresses",
    "/wallet-auth/security",
    "/lnurl/auth",
    "/lnurl/pay",
    "/lnurl/payment-status",
    "/business/access",
    "/business/devices",
    "/business/security",
    "/register/access",
    "/register/devices",
    "/register/refunds",
    "/developers",
    "/operations",
    "/operations/health",
    "/operations/providers",
    "/operations/storage",
    "/operations/incidents",
    "/operations/jobs",
    "/operations/slo",
    "/manifesto",
    "/evidence",
    "/status",
    "/roadmap",
    "/security",
    "/access/security-posture",
    "/websocket-lab",
    "/docs",
    "/check",
    "/trace",
    "/trace/[report_id]",
    "/trace/[report_id]/proof-packet",
)

CONSOLE_ROUTES: tuple[str, ...] = (
    "/console",
    "/console/trace",
    "/console/evidence",
    "/console/provider-health",
    "/console/market-intelligence",
    "/console/time-machine",
    "/console/sovereign-grid",
    "/console/policy",
    "/console/audit",
    "/console/api-explorer",
    "/console/wow",
)

MARKET_ROUTES: dict[str, dict[str, str]] = {
    "/market": {"owner": "reflex", "status": "implemented"},
    "/market/timeline": {"owner": "reflex", "status": "implemented"},
    "/market/time-machine": {"owner": "reflex", "status": "implemented"},
    "/market/signals": {"owner": "reflex", "status": "implemented"},
    "/market/evidence": {"owner": "reflex", "status": "implemented"},
    "/market/narratives": {"owner": "reflex", "status": "implemented"},
    "/market/sources": {"owner": "reflex", "status": "implemented"},
}

STALE_ROUTES: frozenset[str] = frozenset({"/products", "/self-host"})
ALL_REFLEX_ROUTES: tuple[str, ...] = PUBLIC_ROUTES + CONSOLE_ROUTES + tuple(MARKET_ROUTES)
