# ruff: noqa: E501
from __future__ import annotations

import reflex as rx

from bastion_ui.components.auth import (
    dedicated_auth_address_notice,
    device_binding_card,
    device_list,
    lnurl_auth_qr_code,
    lockdown_panel,
    quorum_status_panel,
    recovery_capsule_panel,
    session_status,
    wallet_auth_method_selector,
    wallet_proof_intent_card,
    wallet_security_warning,
    withdraw_safety_panel,
)
from bastion_ui.components.layout.grid import responsive_grid
from bastion_ui.components.ui.card import card
from bastion_ui.routes._shared import public_page


def wallet_auth_page() -> rx.Component:
    return public_page(
        "Wallet-first authentication",
        wallet_auth_method_selector(),
        wallet_security_warning(),
        dedicated_auth_address_notice(),
        subtitle="Proof establishes a Principal; Device Binding and a PoP Session are still required.",
    )


def wallet_register_page() -> rx.Component:
    return public_page(
        "Register a Wallet Principal",
        wallet_proof_intent_card(),
        device_binding_card(),
        wallet_security_warning(),
        subtitle="No email/password account is created. Wallet address is proof input, not global identity.",
    )


def wallet_login_page() -> rx.Component:
    return public_page(
        "Sign in with a wallet",
        wallet_auth_method_selector(),
        session_status(),
        subtitle="A current single-use challenge is required for every proof.",
    )


def wallet_lnurl_page() -> rx.Component:
    return public_page(
        "Sign in with Lightning",
        lnurl_auth_qr_code(),
        responsive_grid(
            *(
                card(rx.text(state), title="Authentication state")
                for state in (
                    "generating",
                    "waiting_for_wallet",
                    "verifying",
                    "wallet_verified",
                    "binding_device",
                    "creating_session",
                    "authenticated",
                    "expired",
                    "rejected",
                    "unsupported_wallet",
                    "error",
                )
            )
        ),
        device_binding_card(),
        subtitle="Bastion verifies k1, action, domain, expiry, replay state, and signature. This browser does not.",
    )


def wallet_bitcoin_page() -> rx.Component:
    return public_page(
        "Sign in with Bitcoin Wallet",
        wallet_proof_intent_card(),
        wallet_security_warning(),
        dedicated_auth_address_notice(),
        device_binding_card(),
        card(
            rx.text(
                "Compatibility signing mode is shown only if backend policy enables legacy_message_signature."
            ),
            rx.text("This lower-assurance method cannot authorize high-risk Bastion operations."),
            title="Legacy message signing",
            variant="safety",
        ),
        subtitle="Sign authentication message—not a transaction. Preferred proof: BIP-322.",
    )


def wallet_session_page() -> rx.Component:
    return public_page(
        "PoP Session",
        session_status(),
        device_binding_card(),
        subtitle="Session signing is centralized; session expiry requires explicit re-authentication.",
    )


def wallet_devices_page() -> rx.Component:
    return public_page(
        "Device management",
        device_list(),
        device_binding_card(),
        subtitle="Effective device status and revocation requirements come from Bastion.",
    )


def wallet_entitlements_page() -> rx.Component:
    fields = (
        "Current plan",
        "Subscription status",
        "Expiration",
        "API limits",
        "Metric groups",
        "Child API key allowance",
        "Offline capability",
        "Security requirements",
    )
    return public_page(
        "Subscription Entitlements",
        responsive_grid(*(card(rx.text("Loaded from backend"), title=field) for field in fields)),
        card(
            rx.text("Available · Upgrade required · Quota exceeded · Metric not allowed"),
            title="Capability states",
        ),
        subtitle="The frontend never calculates permissions from plan name.",
    )


def wallet_step_up_page() -> rx.Component:
    return public_page(
        "Additional approval required",
        card(
            rx.text(
                "Action · requested scopes · expiration · cannot_access · risk · required factor"
            ),
            rx.text(
                "Fresh Bitcoin proof · fresh LNURL-auth · hardware wallet · Bastion Vault · multi-wallet quorum"
            ),
            title="Human Intent step-up",
            variant="safety",
        ),
        lnurl_auth_qr_code("LNURL step-up generated by Bastion"),
        wallet_proof_intent_card(),
        subtitle="The failed action is not automatically retried. Backend approval must complete first.",
    )


def wallet_recovery_page() -> rx.Component:
    return public_page(
        "Recover Bastion access",
        recovery_capsule_panel(),
        card(
            rx.text(
                "Recovery state · required factors · completed factors · cooldown · next permitted action"
            ),
            title="Backend Recovery Capsule status",
        ),
        subtitle="LNURL-auth may be one factor; the browser never declares a high-assurance recovery complete.",
    )


def wallet_lockdown_page() -> rx.Component:
    return public_page(
        "Emergency Lockdown",
        lockdown_panel(),
        recovery_capsule_panel(),
        subtitle="Release requires backend-mandated recovery or high-assurance step-up. No force bypass exists.",
    )


def wallet_subscription_page() -> rx.Component:
    return wallet_entitlements_page()


def wallet_lightning_page() -> rx.Component:
    return wallet_lnurl_page()


def wallet_lightning_pay_page() -> rx.Component:
    from bastion_ui.routes.access import access_checkout_page

    return access_checkout_page()


def wallet_lightning_withdraw_page() -> rx.Component:
    return public_page(
        "Lightning refund or payout",
        withdraw_safety_panel(),
        card(
            rx.text("policy_check · step_up_required · approved · waiting_for_invoice"),
            rx.text("invoice_received · processing · paid · failed · expired"),
            title="Backend payout state",
        ),
        subtitle="The implemented backend has no withdraw-status endpoint; payout completion cannot be polled yet.",
    )


def wallet_lightning_addresses_page() -> rx.Component:
    from bastion_ui.components.auth import lightning_address_card

    return public_page(
        "Lightning Addresses",
        lightning_address_card(),
        card(
            rx.text(
                "Copy address · render local QR · open compatible wallet · preview safe metadata"
            ),
            title="Payment routing tools",
        ),
        subtitle="Lightning Address is a payment endpoint. It is not your Bastion identity.",
    )


def wallet_security_page() -> rx.Component:
    return public_page(
        "Wallet security",
        wallet_security_warning(),
        dedicated_auth_address_notice(),
        session_status(),
        quorum_status_panel(),
        subtitle="Access Integrity is advisory posture, never frontend authorization.",
    )
