from enum import Enum


class TimelineEventType(str, Enum):
    NEWS_EVENT = "NEWS_EVENT"
    NEWS_ARTICLE = "NEWS_ARTICLE"
    BTC_CANDLE = "BTC_CANDLE"
    PRICE_SPIKE = "PRICE_SPIKE"
    VOLATILITY_SPIKE = "VOLATILITY_SPIKE"
    MARKET_SIGNAL = "MARKET_SIGNAL"
    SECURITY_EVENT = "SECURITY_EVENT"
    REGULATORY_EVENT = "REGULATORY_EVENT"
    ETF_EVENT = "ETF_EVENT"
    MACRO_EVENT = "MACRO_EVENT"
    OPERATOR_ACTION = "OPERATOR_ACTION"
    SYSTEM_EVENT = "SYSTEM_EVENT"
    PROVIDER_HEALTH_EVENT = "PROVIDER_HEALTH_EVENT"
    NARRATIVE_EVENT = "NARRATIVE_EVENT"
    LIQUIDITY_EVENT = "LIQUIDITY_EVENT"


class TimelineImportance(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class TimelineVisibility(str, Enum):
    PUBLIC = "PUBLIC"
    INTERNAL = "INTERNAL"
    OPERATOR_ONLY = "OPERATOR_ONLY"


class TimelineSourceKind(str, Enum):
    INTERNAL = "INTERNAL"
    RSS = "RSS"
    MARKET_PROVIDER = "MARKET_PROVIDER"
    OPERATOR = "OPERATOR"
    SYSTEM = "SYSTEM"
    IMPORTED = "IMPORTED"
