from enum import StrEnum


class NewsSourceKind(StrEnum):
    RSS = "RSS"
    API = "API"
    BLOG = "BLOG"
    REGULATORY = "REGULATORY"
    MANUAL = "MANUAL"


class NewsSourceTier(StrEnum):
    SOVEREIGN = "SOVEREIGN"
    BITCOIN_NATIVE = "BITCOIN_NATIVE"
    MARKET_MEDIA = "MARKET_MEDIA"
    REGULATORY = "REGULATORY"
    MACRO = "MACRO"
    SECURITY = "SECURITY"
    COMMUNITY = "COMMUNITY"


class NewsArticleType(StrEnum):
    NEWS = "NEWS"
    ANALYSIS = "ANALYSIS"
    ALERT = "ALERT"
    REGULATORY = "REGULATORY"
    SECURITY = "SECURITY"
    MACRO = "MACRO"
    ETF = "ETF"
    MINING = "MINING"
    LIGHTNING = "LIGHTNING"
    BITCOIN_CORE = "BITCOIN_CORE"


class SentimentLabel(StrEnum):
    POSITIVE = "POSITIVE"
    NEGATIVE = "NEGATIVE"
    NEUTRAL = "NEUTRAL"
    MIXED = "MIXED"
    UNKNOWN = "UNKNOWN"


class NewsEventType(StrEnum):
    ETF_INFLOW = "ETF_INFLOW"
    ETF_OUTFLOW = "ETF_OUTFLOW"
    REGULATORY_SHOCK = "REGULATORY_SHOCK"
    SECURITY_SHOCK = "SECURITY_SHOCK"
    MACRO_LIQUIDITY = "MACRO_LIQUIDITY"
    MINER_EVENT = "MINER_EVENT"
    LIGHTNING_EVENT = "LIGHTNING_EVENT"
    BITCOIN_CORE_EVENT = "BITCOIN_CORE_EVENT"
    MARKET_STRUCTURE = "MARKET_STRUCTURE"
    EXCHANGE_EVENT = "EXCHANGE_EVENT"
    TREASURY_ADOPTION = "TREASURY_ADOPTION"
    UNKNOWN = "UNKNOWN"


class SourceHealthStatus(StrEnum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    FAILING = "FAILING"
    DISABLED = "DISABLED"
