apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: bitcoin-bastion-egress-restricted
  namespace: bitcoin-bastion
spec:
  podSelector: {}
  policyTypes: ["Egress"]
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - {protocol: TCP, port: 5432}
        - {protocol: TCP, port: 6379}
    - to:
        - ipBlock: {cidr: 0.0.0.0/0}
      ports:
        - {protocol: TCP, port: 443}
