apiVersion: batch/v1
kind: Job
metadata:
  name: bitcoin-bastion-secret-leakage-scan
  namespace: bitcoin-bastion
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: scan
          image: ghcr.io/zricethezav/gitleaks:latest
          command: ["/bin/sh","-c","gitleaks dir -v /repo --report-format json --report-path /tmp/gitleaks.json"]
