from enum import Enum


class AttributionType(str, Enum):
    NEWS_EVENT = "NEWS_EVENT"
    ARTICLE_DIRECT = "ARTICLE_DIRECT"
    MACRO_EVENT = "MACRO_EVENT"
    SECURITY_EVENT = "SECURITY_EVENT"
    LIQUIDITY_EVENT = "LIQUIDITY_EVENT"
    REGULATORY_EVENT = "REGULATORY_EVENT"
    INSTITUTIONAL_EVENT = "INSTITUTIONAL_EVENT"
    UNKNOWN = "UNKNOWN"


class CandidateCategory(str, Enum):
    ETF = "ETF"
    FED = "FED"
    SEC = "SEC"
    EXCHANGE = "EXCHANGE"
    MINING = "MINING"
    LIGHTNING = "LIGHTNING"
    BITCOIN_CORE = "BITCOIN_CORE"
    MACRO = "MACRO"
    SECURITY = "SECURITY"
    LIQUIDITY = "LIQUIDITY"
    ADOPTION = "ADOPTION"
    TREASURY = "TREASURY"
    UNKNOWN = "UNKNOWN"
