#!/usr/bin/env python3
"""Generate the reviewed Stage-1B0 representative typed-operation registry."""

from __future__ import annotations

import argparse
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from app.main import app  # noqa: E402

OUT = ROOT / "frontend/bastion_ui/transport/generated_foundation.py"
SELECTED = (
    ("HTTP-0076", "/api/v1/health", "health_api_v1_health_get", "HealthOutDTO", "HealthOut", "health"),
    ("HTTP-0250", "/api/v1/public/status", "public_status_api_v1_public_status_get", "PublicStatusEnvelopeDTO", "ResponseEnvelope_PublicStatusResponse_", "public"),
)


def render() -> str:
    spec = app.openapi()
    head = subprocess.check_output(("git", "rev-parse", "HEAD"), cwd=ROOT, text=True).strip()
    blocks: list[str] = []
    entries: list[str] = []
    for matrix_id, path, operation_id, dto, schema, tag in SELECTED:
        operation = spec["paths"][path]["get"]
        if operation["operationId"] != operation_id:
            raise SystemExit(f"{path}: operation identity changed")
        response = operation["responses"]["200"]["content"]["application/json"]["schema"]
        if response.get("$ref", "").rsplit("/", 1)[-1] != schema:
            raise SystemExit(f"{operation_id}: success schema changed")
        name = operation_id.upper()
        blocks.append(f'''{name}_SECURITY = SecurityMetadata(
    identity="reviewed-public:{operation_id}",
    public=True,
    access_required=False,
    signed_request_required=False,
    human_intent_required=False,
    source_symbol="app.api.v1.{tag}",
    review_owner="Stage 1B0 transport contract",
)
{name} = NormalizedOperation(
    matrix_id="{matrix_id}",
    operation_id="{operation_id}",
    method="GET",
    path="{path}",
    backend_tag="{tag}",
    product="Core",
    disposition="UI_REQUIRED",
    success_status=200,
    response_type={dto},
    security={name}_SECURITY,
    retry_safe=True,
    owner="bastion_ui.transport.generated_foundation:{name}",
)''')
        entries.append(f'''    ContractRegistryEntry(
        registry_id="http:{operation_id}",
        source_head=SOURCE_HEAD,
        operation={name},
        request_schema="NoBody",
        success_schema="{schema}",
    ),''')
    return '''# Generated by python scripts/generate_http_transport_foundation.py --write.\n# Do not edit.\nfrom bastion_ui.transport.foundation import (\n    ContractRegistryEntry,\n    HealthOutDTO,\n    NormalizedOperation,\n    PublicStatusEnvelopeDTO,\n    SecurityMetadata,\n)\n\nSOURCE_HEAD = "''' + head + '''"\n\n''' + "\n\n".join(blocks) + '''\n\nFEATURE_53_FOUNDATION = (\n''' + "\n".join(entries) + ''')\n'''


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUT.exists() or OUT.read_text() != rendered:
            raise SystemExit("generated HTTP transport foundation is stale; run with --write")
        return
    OUT.write_text(rendered)


if __name__ == "__main__":
    main()
