apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitcoinbastion-production
spec:
  project: default
  source:
    repoURL: https://github.com/Hegehub/bitcoinbastion.git
    targetRevision: main
    path: deploy/kubernetes/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: bitcoinbastion
  syncPolicy:
    automated: {}
