# Generated by python scripts/generate_http_transport_foundation.py --write.
# Do not edit.
from bastion_ui.transport.foundation import (
    ContractRegistryEntry,
    HealthOutDTO,
    NormalizedOperation,
    PublicStatusEnvelopeDTO,
    SecurityMetadata,
)

SOURCE_HEAD = "c827464af469c1727f47324d585c1250c65a50dc"

HEALTH_API_V1_HEALTH_GET_SECURITY = SecurityMetadata(
    identity="reviewed-public:health_api_v1_health_get",
    public=True,
    access_required=False,
    signed_request_required=False,
    human_intent_required=False,
    source_symbol="app.api.v1.health",
    review_owner="Stage 1B0 transport contract",
)
HEALTH_API_V1_HEALTH_GET = NormalizedOperation(
    matrix_id="HTTP-0076",
    operation_id="health_api_v1_health_get",
    method="GET",
    path="/api/v1/health",
    backend_tag="health",
    product="Core",
    disposition="UI_REQUIRED",
    success_status=200,
    response_type=HealthOutDTO,
    security=HEALTH_API_V1_HEALTH_GET_SECURITY,
    retry_safe=True,
    owner="bastion_ui.transport.generated_foundation:HEALTH_API_V1_HEALTH_GET",
)

PUBLIC_STATUS_API_V1_PUBLIC_STATUS_GET_SECURITY = SecurityMetadata(
    identity="reviewed-public:public_status_api_v1_public_status_get",
    public=True,
    access_required=False,
    signed_request_required=False,
    human_intent_required=False,
    source_symbol="app.api.v1.public",
    review_owner="Stage 1B0 transport contract",
)
PUBLIC_STATUS_API_V1_PUBLIC_STATUS_GET = NormalizedOperation(
    matrix_id="HTTP-0250",
    operation_id="public_status_api_v1_public_status_get",
    method="GET",
    path="/api/v1/public/status",
    backend_tag="public",
    product="Core",
    disposition="UI_REQUIRED",
    success_status=200,
    response_type=PublicStatusEnvelopeDTO,
    security=PUBLIC_STATUS_API_V1_PUBLIC_STATUS_GET_SECURITY,
    retry_safe=True,
    owner="bastion_ui.transport.generated_foundation:PUBLIC_STATUS_API_V1_PUBLIC_STATUS_GET",
)

FEATURE_53_FOUNDATION = (
    ContractRegistryEntry(
        registry_id="http:health_api_v1_health_get",
        source_head=SOURCE_HEAD,
        operation=HEALTH_API_V1_HEALTH_GET,
        request_schema="NoBody",
        success_schema="HealthOut",
    ),
    ContractRegistryEntry(
        registry_id="http:public_status_api_v1_public_status_get",
        source_head=SOURCE_HEAD,
        operation=PUBLIC_STATUS_API_V1_PUBLIC_STATUS_GET,
        request_schema="NoBody",
        success_schema="ResponseEnvelope_PublicStatusResponse_",
    ),)
