apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: bitcoin-bastion-worker
  namespace: bitcoin-bastion
spec:
  scaleTargetRef:
    name: bitcoin-bastion-worker
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 12
  triggers:
    - type: redis
      metadata:
        address: redis:6379
        listName: celery
        listLength: "20"
