apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bitcoin-bastion-k3s

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patch-env.yaml
  - path: patch-resources.yaml
  - path: patch-ingress-traefik.yaml
  - path: patch-single-node-replicas.yaml
