apiVersion: v1
kind: Namespace
metadata:
  name: bitcoin-bastion-k3s
  labels:
    app.kubernetes.io/name: bitcoin-bastion
    app.kubernetes.io/environment: k3s
    app.kubernetes.io/runtime-profile: k3s
