# ruff: noqa: E501
from __future__ import annotations

import base64
import io

import reflex as rx
import segno

from bastion_ui.components.layout.grid import responsive_grid
from bastion_ui.components.ui.card import card
from bastion_ui.config import get_config


def wallet_security_warning() -> rx.Component:
    return card(
        rx.text("Bastion will never ask for your Bitcoin seed or private key."),
        rx.text("This signature does not authorize a Bitcoin transaction."),
        rx.text("This signature only proves wallet control for Bastion access."),
        title="No-custody authentication",
        subtitle="Wallet proves control. Device establishes continuity. PoP Session protects requests. Policy Engine authorizes actions.",
        variant="safety",
    )


def dedicated_auth_address_notice() -> rx.Component:
    return card(
        rx.text("Use a dedicated Bastion authentication wallet or address."),
        rx.text("Do not use your cold treasury wallet for routine login."),
        title="Dedicated authentication wallet recommended",
        variant="safety",
    )


def wallet_auth_method_selector() -> rx.Component:
    config = get_config()
    return responsive_grid(
        card(
            rx.text("Use LNURL-auth from a compatible Lightning wallet."),
            rx.link("Sign in with Lightning", href="/wallet-auth/lnurl", role="button")
            if config.lnurl_auth_enabled
            else rx.text("LNURL-auth unavailable in this deployment"),
            title="Lightning Wallet",
            subtitle="Lightning proof → Principal → Device Binding → PoP Session",
        ),
        card(
            rx.text(
                "Prove wallet control with BIP-322. Compatibility signing appears only when backend policy allows it."
            ),
            rx.link("Sign in with Bitcoin Wallet", href="/wallet-auth/bitcoin", role="button")
            if config.wallet_auth_enabled
            else rx.text("Bitcoin Wallet Auth unavailable in this deployment"),
            title="Bitcoin Wallet",
            subtitle="BIP-322 proof → Principal → Device Binding → PoP Session",
        ),
    )


def wallet_proof_intent_card() -> rx.Component:
    return card(
        rx.text("Domain · Action · Bitcoin network · Purpose · Device fingerprint · Expiry · Risk"),
        rx.text(
            "Display the complete structured Bastion Auth Intent before external wallet approval."
        ),
        rx.button("Copy authentication message", aria_label="Copy Bastion authentication message"),
        rx.button("Submit signed proof", aria_label="Submit externally signed wallet proof"),
        title="Approve Bastion access proof",
        subtitle="Preferred method: BIP-322. This is not transaction signing.",
    )


def _qr_data_uri(value: str) -> str:
    stream = io.BytesIO()
    segno.make(value, error="m").save(stream, kind="svg", scale=5, xmldecl=False)
    return "data:image/svg+xml;base64," + base64.b64encode(stream.getvalue()).decode()


def lnurl_auth_qr_code(lnurl: str = "LNURL challenge generated by Bastion") -> rx.Component:
    return card(
        rx.image(
            src=_qr_data_uri(lnurl), alt="LNURL authentication QR code", width="min(18rem, 80vw)"
        ),
        rx.text("Domain: backend-provided Bastion authentication domain"),
        rx.text("Action: Login / Register / Step-up"),
        rx.text("Expires: countdown announced when challenge is active", aria_live="polite"),
        rx.text("No Bitcoin transaction is being authorized."),
        rx.link(
            "Open in Lightning wallet",
            href=lnurl,
            aria_label="Open LNURL in a compatible Lightning wallet",
        ),
        rx.button("Copy encoded LNURL", aria_label="Copy encoded LNURL"),
        title="Scan with a Lightning wallet",
        subtitle="The QR expires with the single-use backend challenge. Generate a new challenge after expiry.",
    )


def device_binding_card() -> rx.Component:
    return card(
        rx.text(
            "New device detected. Wallet verification is required before this device can become trusted."
        ),
        rx.text(
            "Browser is not a root of trust for critical actions. A secure platform/Vault signer may be required."
        ),
        title="Device Binding",
        variant="safety",
    )


def session_status() -> rx.Component:
    return card(
        rx.text(
            "Session states: active · expiring · expired · revoked · frozen · lockdown · recovery_only"
        ),
        rx.link("Re-authenticate", href="/wallet-auth", role="button"),
        title="Device-bound PoP Session",
        subtitle="Wallet or LNURL proof alone does not unlock protected data.",
    )


def device_list() -> rx.Component:
    return card(
        rx.text(
            "Device name · class · status · first bound · last seen · verification strength · risk"
        ),
        rx.button("Revoke selected device", aria_label="Revoke selected Bastion device"),
        title="Trusted devices",
        subtitle="Private Device Keys are never displayed. Revocation may require fresh step-up.",
    )


def subscription_plan_card(name: str, code: str, description: str) -> rx.Component:
    action = (
        rx.link("Choose plan", href=f"/access/checkout?plan={code}", role="button")
        if get_config().lnurl_pay_enabled
        else rx.text("LNURL-pay unavailable in this deployment")
    )
    return card(rx.text(description), action, title=name)


def lnurl_payment_status() -> rx.Component:
    return card(
        rx.text("Invoice created: not access"),
        rx.text("Payment confirmed: backend settlement verification"),
        rx.text("Bastion access activated: backend entitlement issued", aria_live="polite"),
        title="Payment status",
        subtitle="QR scanned or invoice issued never activates a subscription.",
    )


def lightning_address_card() -> rx.Component:
    return card(
        rx.text(
            "lite@bitcoin-bastion.com · basic@bitcoin-bastion.com · plus@bitcoin-bastion.com · pro@bitcoin-bastion.com"
        ),
        rx.text(
            "Lightning Address is payment routing UX. It is not identity and does not authenticate a Principal."
        ),
        title="Pay with Lightning Address",
    )


def recovery_capsule_panel() -> rx.Component:
    return card(
        rx.text(
            "Recover Bastion access using backend-approved wallet proof, LNURL factor, trusted device, recovery file, hardware wallet, or quorum."
        ),
        rx.text("Never enter your Bitcoin seed or private key into Bastion."),
        rx.text("Bastion Recovery material is not your Bitcoin wallet seed."),
        title="Recovery Capsule",
        variant="safety",
    )


def lockdown_panel() -> rx.Component:
    return card(
        rx.text(
            "Freeze sessions · disable child keys · revoke delegated passes · disable PayRegister admin · invalidate offline packs"
        ),
        rx.checkbox(
            "I understand that recovery or wallet step-up may be required to restore access."
        ),
        rx.button("Enter Emergency Lockdown", aria_label="Confirm Emergency Lockdown"),
        title="Emergency Lockdown",
        subtitle="This is not ordinary logout. Backend Policy Engine and audit remain authoritative.",
        variant="safety",
    )


def withdraw_safety_panel() -> rx.Component:
    return card(
        rx.text("Amount range · purpose · requested action · beneficiary context"),
        rx.text("Policy status · approval state · expiry"),
        rx.text("This withdraw request can result in a Lightning payment."),
        rx.text("Only continue if you initiated this refund or payout."),
        title="Policy-gated Lightning withdraw",
        subtitle="No valuable QR is displayed until backend policy_approved is true.",
        variant="safety",
    )


def quorum_status_panel() -> rx.Component:
    return card(
        rx.text("Required: backend-defined 2-of-3 or 3-of-5"),
        rx.text("Approved: role pseudonym · proof strength · timestamp"),
        rx.text("Waiting: additional independent method or wallet"),
        title="Multi-method quorum",
        subtitle="Duplicate signers are not counted locally; backend quorum is authoritative.",
    )


def security_state_banner(state: str, message: str) -> rx.Component:
    return card(
        rx.text(message, role="status", aria_live="polite"),
        title=state.replace("_", " ").title(),
        variant="safety"
        if state in {"device_revoked", "lockdown_active", "recovery_lock_active"}
        else "default",
    )
