apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target: {kind: ConfigMap, name: app-config}
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: staging
      - op: replace
        path: /data/DEBUG
        value: "false"
  - target: {kind: Ingress, name: bitcoinbastion}
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging.bitcoinbastion.example.com
